#! /bin/bash

# dclip-1.2 || Delta 05ene09

file=$HOME/.dclip_cache
size=10

touch $file 

case $1 in
    "copy")
        sel_clip=$(xclip -o)
        sel_file=$(echo -n "$sel_clip"|tr '\n' '\034')
        ;;
    "paste")
        shift 
        linecount=$(wc -l $file | egrep -o "^[[:digit:]]+")
        echo $linecount
        sel_file=$(cat $file | dmenu -l $linecount ${1+"$@"}) 
        if [ ! $sel_file ] ; then
            exit
        fi
        sel_clip=$(echo -n "$sel_file"|tr '\034' '\n')
        echo -n "${sel_clip%\\n}" | xvkbd -xsendevent -file -
        
        ;;
    *)
        exit
        ;;
esac
cut=$(head -n $(($size-1)) $file)
echo "$sel_file" > $file
echo -n "${cut//"$sel_file"/}" | sed '/^$/d' >> $file

echo -n "$sel_clip" | xclip -selection clipboard -i

exit 0
