#!/bin/sh

ASK_SECTION=false
BG_COLOR=#000000 #solarized light gray
FG_COLOR=#858900 #solarized green
SEL_BG_COLOR=$FG_COLOR
SEL_FG_COLOR=$BG_COLOR
FONT="Noto Sans Mono CJK JP Regular:pixelsize=10"

my_dmenu ()
{
    local prompt=${1:-"Man:"}
    local height=${2:-4}
    LANG=en_US.UTF-8 dmenu -p $prompt -nf $FG_COLOR -nb $BG_COLOR -sb $SEL_BG_COLOR -sf $SEL_FG_COLOR -i -l 10 -fn "$FONT"
}

page_section=`man -k . | my_dmenu "$@" | sed -r 's/^([^ ]+) \(([^)]+)\).*$/\1 \2/'`

page=${page_section%% *}
section=${page_section##* }
echo $page
echo $section

if [ ! $page ] ; then
    exit
fi

my-term -e man $section $page 
