#!/bin/sh

export MANSECT=1,3,7
ASK_SECTION=false
BG_COLOR=#000000 #solarized light gray
FG_COLOR=#858900 #solarized green
SEL_BG_COLOR=$FG_COLOR
SEL_FG_COLOR=$BG_COLOR
FONT="Sazanami Mincho:pixelsize=10"

my_dmenu ()
{
    local prompt=${1:-"Man:"}
    local height=${2:-4}
    LANG=en_US.UTF-8 dmenu -p $prompt -nf $FG_COLOR -nb $BG_COLOR -sb $SEL_BG_COLOR -sf $SEL_FG_COLOR -i -l 10 -fn "$FONT"
}

page_section=`man -k . | my_dmenu "$@" | sed -r 's/^([^ ]+) \(([[:digit:]]+)\).*$/\1 \2/'`
echo "ps = $page_section"
page=${page_section%% *}
section=${page_section##* }

if [ ! $page ] ; then
    exit
fi
echo "section =${section}"
yelp "man:$page\(${section}\)"
