#!/bin/bash

## Get screen info
monitor_data=$(xrandr | grep -w connected  | sed -r 's/ +primary +/ /g' | awk -F'[ +]' '{print $1,$3,$4}')
# TODO: Make this work for N>2 screens
screen1=($(echo "$monitor_data" | head -n 1))
screen2=($(echo "$monitor_data" | tail -n 1))

## Figure out which screen is to the right of which
if [ ${screen1[2]} -eq 0  ]
then
    right=(${screen2[@]});
    left=(${screen1[@]});
else
    right=(${screen1[@]});
    left=(${screen2[@]});

fi

## Get window position
pos=$(xwininfo -id $(xdotool getactivewindow) | grep "Absolute upper-left X" | 
      awk '{print $NF}')

## Which screen is this window displayed in? If $pos
## is greater than the offset of the rightmost screen,
## then the window is on the right hand one
if [ "$pos" -ge "${right[2]}" ]
then
    echo "${right[0]}"    
else
    echo "${left[0]}"    
fi
