#!/bin/sh
$(import util.sh)
$(import wacom_util.sh)
die_if_program_doesnt_exist xsetwacom

if [ ! "$1" ] ; then
    OUTPUT=$(get-cursor-monitor)
fi

OUTPUT=${OUTPUT:-LVDS-1}

eraser=$(wacom_get_device_id ERASER)
stylus=$(wacom_get_device_id STYLUS)
xsetwacom --set "$eraser" MapToOutput $OUTPUT
xsetwacom --set "$stylus" MapToOutput $OUTPUT
