#!/bin/sh

error () {
    echo $@ >&2
}

which inotifywait 2>/dev/null >&2
if [ $? -ne 0 ] ; then
    error "inotifywait is not available. Exiting."
    exit 8
fi

which map-wacom 2>/dev/null >&2
if [ $? -ne 0 ] ; then
    error "map-wacom is not available. Exiting."
    exit 9
fi

dowait () {
    inotifywait $@ 2>/dev/null >&2
}

var_loop () {
    base="$1"
    while [ 1 ] ; do
        if [ -f "$base/wacom-status" ] ; then
            dowait "$base/wacom-status"
            if [ $? -eq 0 ] ; then
                while [ -z "$(xsetwacom --list)" ] ; do
                    sleep .1
                done
                map-wacom
            else
                echo "Inotify error. Exiting" >&2
                exit 2
            fi
        else
            error "Couldn't find the status file. Waiting for it to be created"
            dowait -e create "$base"
        fi
    done

}

if [ -d /var/run ] ; then 
    var_loop /var/run
elif [ -d /run ] ; then
    var_loop /run
else
    error "No /var/run/ and no /run directory was found. Exiting."
    exit 3
fi
