#!/bin/bash

script="$0"
scriptdir="$(readlink -f $(dirname "$0"))"

if [ "$1" ] ; then
    dir=$1
    shift
else
    dir='.'
fi

/usr/bin/du --all -k -x -d 1 "$dir" $@ | sort -nr | /usr/bin/perl $scriptdir/human_bytes.pl
