#!/bin/sh

random_string()
{
    cat /dev/urandom | tr -dc "a-zA-Z0-9${2}" | fold -w ${1:-32} | head -n 1
}

length=$1
extra_charset=$2

str=$(random_string $length $extra_charset)
if [ $DMENU_RUN ] ; then
    xvkbd -no-sync -text "$str"
else
    echo $str 
fi
