#!/bin/sh
$(import util.sh)
$(import wacom_util.sh)
#   2
#   3
#   8
#   9
#4( 1)5
#  10
#  11
#  12
#  13
setkeys () {
    xsetwacom --set $(wacom_get_device_id PAD) Button 13 "key ctrl shift p ctrl shift"
    xsetwacom --set $(wacom_get_device_id PAD) Button 12 "key ctrl shift h ctrl shift"
    xsetwacom --set $(wacom_get_device_id PAD) Button 11 "key ctrl shift t ctrl shift"
    xsetwacom --set $(wacom_get_device_id PAD) Button 10 "key ctrl shift l ctrl shift"
    xsetwacom --set $(wacom_get_device_id TOUCH) Touch off
}

die_if_program_doesnt_exist xsetwacom
on_wacom_status_change setkeys
