#!/bin/sh

PROG=`basename $0`
HOLDER_FILE="$HOME/.cache/vgaon-last-config"
if [ "$PROG" = 'vgaon' ] ; then
    VGA_CONFIG="${VGA_CONFIG:-$HOME/.vgaconf}"
else
    if [ -s "$HOLDER_FILE" ] ; then
        LAST_CONFIG="$(cat "$HOLDER_FILE")"
        if [ -s "$LAST_CONFIG" ] ; then
            VGA_CONFIG="${LAST_CONFIG}"
        fi
    fi
    if [ ! $VGA_CONFIG ] ; then
        VGA_CONFIG="$HOME/.vgaconf"
    fi
fi

echo -n "$VGA_CONFIG" | tee "$HOLDER_FILE"
. "`readlink -f "$VGA_CONFIG"`"
MON=${MON:-LVDS1}
MODE=${MODE:-1366x768}
if [ "$PROG" = hdmioff ] ; then
    EXTMODE=${EXTMODE:-1600x900}
    EXTMON=${EXTMON:-"HDMI-1"}
else
    EXTMODE=${EXTMODE:-1024x768}
    EXTMON=${EXTMON:-VGA-1}
fi
POS=${POS:-below}

srun() {
    sleep 0.5
    echo Running %$@%
    $@
}
type SETUP > /dev/null 2> /dev/null
if [ $? -eq 0 ] ; then
    SETUP
fi

PROG=`basename $0`

if [ $PROG = 'vgaon' -o $PROG = 'vgareset' ] ; then
    srun xrandr --output $EXTMON --off
    srun xrandr --output $EXTMON --mode $EXTMODE
    srun xrandr --output $EXTMON --rotate normal --preferred 
    type AFTER_EXT > /dev/null 2> /dev/null
    if [ $? -eq 0 ] ; then
        AFTER_EXT
    fi
    srun xrandr --output $MON --primary
    srun xrandr --output $MON --mode $MODE
    srun xrandr --output $MON --rotate normal --${POS} $EXTMON
    srun $HOME/.fehbg

    type AFTER > /dev/null 2> /dev/null
    if [ $? -eq 0 ] ; then
        AFTER
    fi
else
    srun xrandr --output $EXTMON --off
    srun "$HOME/.fehbg"
    type AFTER_OFF > /dev/null 2> /dev/null
    if [ $? -eq 0 ] ; then
        AFTER_OFF
    fi
fi
